### ISSUE TITLE
Internal imports are not working as expected

### ISSUE THREAD

**Issue by maike93he** [rl-institut/tracbev#23]
Imports are missing `tracbev`. Whenever I am trying to run tracbev I get an error that the modules are not existing. For example following line:

https://github.com/rl-institut/tracbev/blob/389167b3ed6500cfe03b8deaeb643381ca3b4c60/tracbev/__main__.py#L9

should be changed to: `import tracbev.usecase as uc`

**Comment by mosc5** [comment]
Thanks for the report, i'm gonna fix that immediately. I will also implement testing to catch those types of issues in the future
